"""
chess_engine.book -- a small OPENING BOOK for the classical engine, generated by Stockfish.

Why: at the shallow depth a pure-python engine reaches in interactive time, the OPENING is where it
is weakest (long-term plans a 4-5 ply search cannot see). A book sidesteps search there entirely:
each stored position maps to a strong (Stockfish-labelled) move, played instantly. This is a genuine
Elo lever at ZERO search cost -- and it is MEASURED head-to-head before being shipped (the integrity
rule), exactly like the eval upgrade.

Book key = `board.epd()` (piece placement + side + castling + en-passant; no move counters), so it
matches transposed positions too. Values are UCI strings. Stored as JSON (human-readable, diffable).

  from chess_engine.book import OpeningBook
  book = OpeningBook.load("chess_engine/opening_book.json")
  mv = book.get(board)                 # a chess.Move if the position is in book and legal, else None

  python -m chess_engine.book --generate --out chess_engine/opening_book.json --lines 50 --max-ply 12

No emoji (Windows cp1252).
"""
from __future__ import annotations

import json
import os
import random
from typing import Optional

import chess


def book_key(board: chess.Board) -> str:
    """Position identity for the book (ignores the halfmove/fullmove counters)."""
    return board.epd()


class OpeningBook:
    def __init__(self, moves: Optional[dict] = None):
        self.moves = dict(moves) if moves else {}

    def __len__(self) -> int:
        return len(self.moves)

    def get(self, board: chess.Board) -> Optional[chess.Move]:
        """The book move for `board` (a legal chess.Move), or None if not in book / illegal."""
        uci = self.moves.get(book_key(board))
        if not uci:
            return None
        try:
            mv = chess.Move.from_uci(uci)
        except ValueError:
            return None
        return mv if mv in board.legal_moves else None

    def save(self, path: str) -> None:
        with open(path, "w", encoding="ascii") as f:
            json.dump(self.moves, f, indent=0, sort_keys=True)

    @classmethod
    def load(cls, path: str) -> "OpeningBook":
        if not path or not os.path.exists(path):
            return cls({})
        with open(path, "r", encoding="ascii") as f:
            return cls(json.load(f))


def generate(sf_path: str, n_lines: int = 50, max_ply: int = 12, eps: float = 0.35,
             movetime: float = 0.15, seed: int = 0, verbose: bool = True) -> dict:
    """Build a book dict (epd -> uci) by exploring the opening with Stockfish. At each visited
    position we STORE Stockfish's best move (the book recommendation); we CONTINUE the line by
    playing that best move most of the time, or a random legal move with prob `eps` (for breadth,
    so the book covers more than one principal line)."""
    import chess.engine
    rng = random.Random(seed)
    sf = chess.engine.SimpleEngine.popen_uci(sf_path)
    book: dict = {}
    try:
        for li in range(n_lines):
            board = chess.Board()
            for _ply in range(max_ply):
                if board.is_game_over():
                    break
                res = sf.play(board, chess.engine.Limit(time=movetime))
                best = res.move
                if best is None:
                    break
                book[book_key(board)] = best.uci()          # store the strong move at this position
                if rng.random() < eps:                       # breadth: sometimes deviate
                    board.push(rng.choice(list(board.legal_moves)))
                else:
                    board.push(best)
            if verbose and (li + 1) % 10 == 0:
                print(f"  line {li + 1}/{n_lines}: book has {len(book)} positions", flush=True)
    finally:
        sf.quit()
    return book


def main() -> int:
    import argparse
    from chess_engine.sf_engine import find_stockfish
    ap = argparse.ArgumentParser(description="Generate a Stockfish opening book for the classical engine.")
    ap.add_argument("--generate", action="store_true")
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "opening_book.json"))
    ap.add_argument("--lines", type=int, default=50)
    ap.add_argument("--max-ply", type=int, default=12)
    ap.add_argument("--eps", type=float, default=0.35)
    ap.add_argument("--movetime", type=float, default=0.15)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    sf = find_stockfish()
    if not sf:
        print("[book] no Stockfish binary found (set STOCKFISH_PATH or put it in engines/).")
        return 1
    if args.generate:
        print(f"[book] generating from {sf} -- {args.lines} lines x {args.max_ply} ply "
              f"@ {args.movetime}s ...", flush=True)
        moves = generate(sf, n_lines=args.lines, max_ply=args.max_ply, eps=args.eps,
                         movetime=args.movetime, seed=args.seed)
        OpeningBook(moves).save(args.out)
        print(f"[book] wrote {len(moves)} positions -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
