"""Shared threshold loader for alt-bar builders.

Single source of truth for per-asset thresholds across DIB / adaptive_vol /
tick_runs / vol_runs builders. Resolves in this order:

  1. Explicit hardcoded table in the builder (preserves u10 hand-tuning)
  2. Per-asset override in config/alt_bar_thresholds.yaml
  3. Tier-based default in config/alt_bar_thresholds.yaml
  4. Hardcoded safe fallback

Generated by scripts/oracle/derive_alt_bar_thresholds.py from
config/universes/u50.yaml + u100.yaml median_dollar_vol_30d values.

NOTE on vol_runs: the per-asset and tier defaults for vol_runs are derived
from a coarse avg-price proxy (per liquidity_tier). For production use,
recompute these from per-asset aggTrades volume scans. For first-pass
exhaust, tick_runs is the preferred consensus-flow signal.
"""
from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Literal

import yaml

# 2026-05-15 R35: canonical universe access via UniverseLoader (alignment).
# This file historically reads config/universes/*.yaml directly. The yaml read
# remains for fields not yet wrapped (DNA, liquidity_tier metadata); the
# UniverseLoader import below documents the canonical access point for
# asset-list enumeration. Future: migrate yaml.safe_load paths to
# UniverseLoader methods (.list, .dna_for, .liquidity_tier, .position_cap).
try:
    import sys as _r35_sys
    from pathlib import Path as _r35_Path
    _r35_SRC = _r35_Path(__file__).resolve().parent
    while _r35_SRC.name and not (_r35_SRC / "pipeline" / "universe_loader.py").exists() and _r35_SRC != _r35_SRC.parent:
        _r35_SRC = _r35_SRC.parent
    if str(_r35_SRC) not in _r35_sys.path:
        _r35_sys.path.insert(0, str(_r35_SRC))
    from pipeline.universe_loader import UniverseLoader  # noqa: F401 (canonical access marker)
except ImportError:
    UniverseLoader = None  # type: ignore[assignment]


__contract__ = {
    "kind": "support",
    "inputs": {
        "files": ["config/alt_bar_thresholds.yaml"],
    },
    "outputs": {
        "callable": "get_threshold(symbol, bar_type, liquidity_tier=None) -> float",
    },
    "invariants": {
        "fallback_chain": ["yaml_per_asset", "yaml_tier_default", "hardcoded_safe"],
        "no_silent_failure": "missing yaml falls back to hardcoded safe defaults",
    },
}

_ROOT = Path(__file__).resolve().parents[3]
_CONFIG_PATH = _ROOT / "config" / "alt_bar_thresholds.yaml"

BarType = Literal["dib", "adaptive_vol_base", "tick_runs", "vol_runs"]

# Hardcoded safe fallbacks (used when yaml isn't loadable).
_SAFE_FALLBACK: dict[BarType, float] = {
    "dib": 500_000.0,
    "adaptive_vol_base": 2_000_000.0,
    "tick_runs": 1_000.0,
    "vol_runs": 100_000.0,
}

# Yaml key for each bar type (per_asset / tier_defaults sections use different
# trailing suffix conventions).
_PER_ASSET_KEY = {
    "dib": "dib_threshold_usd",
    "adaptive_vol_base": "adaptive_vol_base_threshold_usd",
    "tick_runs": "tick_runs_threshold",
    "vol_runs": "vol_runs_threshold",
}
_TIER_DEFAULTS_KEY = {
    "dib": "dib_threshold_usd_by_tier",
    "adaptive_vol_base": "adaptive_vol_base_threshold_usd_by_tier",
    "tick_runs": "tick_runs_threshold_by_tier",
    "vol_runs": "vol_runs_threshold_by_tier",
}


@lru_cache(maxsize=1)
def _load_yaml() -> dict:
    if not _CONFIG_PATH.exists():
        # Warn once (lru_cache(1) ensures single emission): all assets will fall
        # through to hardcoded safe fallbacks, which can be far from tuned values.
        print(f"[_thresholds] WARN config {_CONFIG_PATH} missing; using hardcoded "
              f"fallback thresholds for ALL assets", flush=True)
        return {}
    try:
        with open(_CONFIG_PATH) as f:
            return yaml.safe_load(f) or {}
    except Exception as exc:
        print(f"[_thresholds] WARN failed to load {_CONFIG_PATH}: {exc}", flush=True)
        return {}


def get_threshold(symbol: str,
                  bar_type: BarType,
                  liquidity_tier: str | None = None) -> float:
    """Resolve threshold for (symbol, bar_type).

    Args:
        symbol: e.g. "BTCUSDT"
        bar_type: "dib" | "adaptive_vol_base" | "tick_runs" | "vol_runs"
        liquidity_tier: optional tier hint (TIER_B / TIER_C / EVENT_ONLY). If not
            provided, will try to read from yaml per_asset entry.

    Returns:
        Threshold value (USD for dib/adaptive_vol; count for runs).
    """
    cfg = _load_yaml()
    if not cfg:
        return _SAFE_FALLBACK[bar_type]

    # 1) Per-asset override
    per_asset = cfg.get("per_asset", {}).get(symbol)
    if per_asset:
        key = _PER_ASSET_KEY[bar_type]
        if key in per_asset:
            return float(per_asset[key])
        # tier hint from per_asset entry if explicit tier wasn't passed
        if liquidity_tier is None:
            liquidity_tier = per_asset.get("liquidity_tier")

    # 2) Tier-based default
    tier_defaults = cfg.get("tier_defaults", {}).get(_TIER_DEFAULTS_KEY[bar_type], {})
    if liquidity_tier and liquidity_tier in tier_defaults:
        return float(tier_defaults[liquidity_tier])

    # 3) Last resort: most conservative tier default (EVENT_ONLY)
    if "EVENT_ONLY" in tier_defaults:
        return float(tier_defaults["EVENT_ONLY"])

    # 4) Hardcoded safe fallback
    return _SAFE_FALLBACK[bar_type]


def known_assets() -> list[str]:
    """Return list of symbols with per-asset threshold entries."""
    cfg = _load_yaml()
    return sorted(cfg.get("per_asset", {}).keys())
