"""UserPromptSubmit hook: @browser routing tag + fuzzy-match typo suggestion.

This hook fires on every user prompt submission. It does TWO things:

1. **@browser tag injection** (existing behavior, preserved): if the prompt
   doesn't already begin with "@browser", inject a system reminder that
   the @browser routing tag applies per project convention.

2. **Fuzzy slash-command suggestion** (NEW, 2026-05-22): if the prompt
   begins with `/<token>` and `<token>` doesn't match any registered skill
   (project or built-in), run the alias+fuzzy matcher and append context
   telling Claude what the user likely meant.

The hook CANNOT rewrite the prompt -- `UserPromptSubmit` only supports
`decision` (block/allow), `reason`, `additionalContext`, `sessionTitle`,
`suppressOriginalPrompt`. Verified against
https://code.claude.com/docs/en/hooks. So the fuzzy layer works by
*telling Claude* about the typo via additionalContext; Claude then
invokes the canonical skill via the Skill tool.

The alias layer is handled at the harness level via stub SKILL.md files
generated by `scripts/gen_alias_stubs.py` (no hook involvement needed
because the harness exact-matches the alias directly).

Stdin schema (from Claude Code):
    {"prompt": "<text>", "session_id": "...", ...}

Stdout schema:
    {"hookSpecificOutput": {
        "hookEventName": "UserPromptSubmit",
        "additionalContext": "<accumulated context, possibly empty>"
    }}

Exit code 0 always. Errors in the matcher are swallowed and logged to
stderr; the hook degrades to pass-through (empty additionalContext)
rather than blocking the prompt.
"""
from __future__ import annotations
import json
import re
import subprocess
import sys
from pathlib import Path


BROWSER_TAG_NOTICE = (
    "[Routing tag: @browser - applied automatically per project convention. "
    "Treat this prompt as @browser-tagged.]"
)


def repo_root() -> Path:
    # crypto/scripts/hooks/ -> crypto sub-project root (where scripts/ lives)
    return Path(__file__).resolve().parent.parent.parent


def claude_root() -> Path:
    # the shared .claude/ lives at the PARENT root (parent of crypto/) after the 3-way split
    return repo_root().parent


def project_skills() -> set[str]:
    """Names of skills with a SKILL.md under .claude/skills/ (post-alias-stub-generation)."""
    skills_root = claude_root() / ".claude" / "skills"
    if not skills_root.exists():
        return set()
    out = set()
    for p in skills_root.iterdir():
        if p.is_dir() and not p.name.startswith("_") and (p / "SKILL.md").exists():
            out.add(p.name.lower())
    return out


def harness_builtins() -> set[str]:
    """Built-in skills shipped with the harness, listed in SKILL_ALIASES.yaml.

    These names are also valid /<token> targets at the harness level even
    though they don't have a .claude/skills/<name>/ directory.
    """
    aliases_path = claude_root() / ".claude" / "skills" / "_common" / "SKILL_ALIASES.yaml"
    if not aliases_path.exists():
        return set()
    out: set[str] = set()
    current_canonical: str | None = None
    for line in aliases_path.read_text(encoding="utf-8").splitlines():
        s = line.rstrip()
        if not s or s.lstrip().startswith("#"):
            continue
        if not s.startswith(" ") and not s.startswith("\t") and s.endswith(":"):
            current_canonical = s[:-1].strip()
            continue
        stripped = s.strip()
        if stripped.startswith("- ") and current_canonical == "__builtins__":
            alias_raw = stripped[2:].strip()
            if "#" in alias_raw:
                alias_raw = alias_raw.split("#", 1)[0].strip()
            if alias_raw:
                out.add(alias_raw.lower())
    return out


SLASH_TOKEN_RE = re.compile(r"^\s*/([A-Za-z][A-Za-z0-9_\-]*)\b")
CLI_BUILTINS = {"help", "clear", "config", "model", "cost", "compact", "memory", "exit", "quit"}


def detect_unmatched_slash(prompt: str) -> str | None:
    """Return the unmatched /<token> name if prompt starts with one, else None.

    Returns None if:
    - prompt doesn't start with `/<token>` (after optional leading whitespace)
    - `<token>` matches a project skill OR a harness built-in
    - `<token>` is a CLI built-in (help/clear/config/etc.) handled by the harness
    """
    m = SLASH_TOKEN_RE.match(prompt)
    if not m:
        return None
    token = m.group(1).lower()
    if token in CLI_BUILTINS:
        return None
    if token in project_skills():
        return None
    if token in harness_builtins():
        return None
    return token


def fuzzy_suggest(token: str) -> tuple[str, float, str] | None:
    """Call scripts/fuzzy_slash_match.py and parse its TSV output.

    Returns (resolved_name, similarity, source) where source in
    {'exact','alias','fuzzy'}, or None if NO_MATCH or matcher unavailable.
    """
    matcher = repo_root() / "scripts" / "fuzzy_slash_match.py"
    if not matcher.exists():
        return None
    try:
        proc = subprocess.run(
            [sys.executable, str(matcher), token],
            capture_output=True, text=True, timeout=5,
            creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
        )
    except (subprocess.TimeoutExpired, OSError) as e:
        print(f"[user_prompt_router] fuzzy matcher failed: {e}", file=sys.stderr)
        return None
    out = proc.stdout.strip()
    if not out:
        return None
    parts = out.split("\t")
    if len(parts) < 4:
        return None
    _query, resolved, sim_str, src = parts[0], parts[1], parts[2], parts[3]
    if resolved == "NO_MATCH":
        return None
    try:
        sim = float(sim_str)
    except ValueError:
        return None
    return (resolved, sim, src)


def build_fuzzy_context(token: str) -> str | None:
    """Return additionalContext text for the typo suggestion, or None if no useful suggestion."""
    suggestion = fuzzy_suggest(token)
    if suggestion is None:
        return None
    resolved, sim, src = suggestion
    if sim >= 0.90:
        action = (
            f"Auto-route: invoke `Skill(skill=\"{resolved}\")` with the user's task. "
            f"Note the correction in your response: \"Routed `/{token}` → `/{resolved}` "
            f"(similarity {sim:.2f}, source={src})\"."
        )
    elif sim >= 0.70:
        action = (
            f"Ask once with default-yes: \"Did you mean `/{resolved}`? "
            f"(typed `/{token}`, similarity {sim:.2f}). Invoking unless you object.\" "
            f"If no objection in the same turn, invoke `Skill(skill=\"{resolved}\")`."
        )
    elif sim >= 0.55:
        action = (
            f"Ask explicitly with default-no: \"Closest match is `/{resolved}` "
            f"(similarity {sim:.2f}). Which did you mean?\" Do NOT auto-invoke."
        )
    else:
        return None
    return (
        f"[SLASH-ROUTER] User typed `/{token}` -- no exact match in skill registry. "
        f"Fuzzy/alias resolver suggests `/{resolved}` at similarity {sim:.3f} (source: {src}). "
        f"Action: {action}"
    )


def main() -> int:
    try:
        data = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError) as e:
        print(f"[user_prompt_router] failed to parse stdin JSON: {e}", file=sys.stderr)
        print(json.dumps({}))
        return 0

    prompt = data.get("prompt", "")
    prompt_lstripped = prompt.lstrip()

    contexts: list[str] = []

    # Layer 1: @browser tag (existing behavior, preserved)
    if not prompt_lstripped.lower().startswith("@browser"):
        contexts.append(BROWSER_TAG_NOTICE)

    # Layer 2: fuzzy slash-command suggestion for unmatched /<token>
    token = detect_unmatched_slash(prompt_lstripped)
    if token is not None:
        fuzzy_ctx = build_fuzzy_context(token)
        if fuzzy_ctx is not None:
            contexts.append(fuzzy_ctx)

    if not contexts:
        print(json.dumps({}))
        return 0

    out = {
        "hookSpecificOutput": {
            "hookEventName": "UserPromptSubmit",
            "additionalContext": "\n\n".join(contexts),
        }
    }
    print(json.dumps(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
