#!/usr/bin/env python
"""
_mine_user_wants.py -- streaming extractor of GENUINE user-typed text from the
Claude Code transcript corpus.

Reads every .jsonl transcript LINE BY LINE (json.loads per line; NEVER loads a
whole file), keeps only real user-typed messages, strips auto-injected wrappers
(system-reminder, ide_opened_file, hook context, Stop-hook feedback, Caveat,
and the pasted SKILL.md body that follows a <command-name>), and emits one
compact record per genuine user message to runs/autonomy/_user_messages.jsonl.

RWYB tool -- reusable. No emoji (cp1252-safe). Absolute paths only.

Usage:
    python scripts/autonomy/_mine_user_wants.py
"""
import json
import os
import re
import sys
import glob

CORPUS_DIR = r"C:/Users/karab/.claude/projects/c--Users-karab-Documents-coding-v4-crypto-stystem"
OUT_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                        "runs", "autonomy", "_user_messages.jsonl")  # crypto/runs/... (autonomy->scripts->crypto)
# NOTE: CORPUS_DIR above is the EXTERNAL Claude project memory dir (encoded launch-cwd path); it is
# updated by the split runbook when the parent is renamed (the encoded name changes).

MAX_TEXT = 600

# Auto-injected wrapper markers: if a text block STARTS with (or is dominated by)
# one of these, it is harness-injected context, not user typing.
WRAPPER_PREFIXES = (
    "<system-reminder>",
    "<ide_opened_file>",
    "<ide_selection>",
    "<ide_diagnostics>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<task-notification>",       # Monitor event injection, not user-typed
    "Caveat:",
    "Stop hook feedback",
    "[Request interrupted",
    "[Tool ",
    "API Error",
    "This session is being continued",
    "Your task is to create a detailed summary",
    "<budget:",
    # autogenerated skill-stub bodies pasted as the first text block
    "Base directory for this skill",
)

# Agent-dispatch / worker-prompt bodies. These are prompts the META instance
# wrote to dispatch a SUB-AGENT (or an autonomy-graph node prompt), NOT genuine
# user typing. If a block opens with one of these it is an agent brief.
AGENT_PROMPT_PREFIXES = (
    "You are a ",
    "You are an ",
    "You are the ",
    "You are Claude",
    "You are operating",
    "You are running",
    "You are a reasoning node",
)

# Substrings strongly indicating an agent-dispatch brief regardless of opener.
AGENT_PROMPT_CONTAINS = (
    "worker agent for the V4",
    "reasoning node in an autonomous",
    "AUTOGENERATED by scripts",
    "sub-agent",
)

# Substrings that, if present anywhere early, mark a wrapper-only block.
WRAPPER_CONTAINS = (
    "<system-reminder>",
    "UserPromptSubmit",
    "Stop hook feedback",
)

CMD_NAME_RE = re.compile(r"<command-name>\s*(/?[^<\n]+?)\s*</command-name>", re.S)
CMD_ARGS_RE = re.compile(r"<command-args>(.*?)</command-args>", re.S)
TAG_STRIP_RE = re.compile(r"<command-message>.*?</command-message>", re.S)


def strip_system_reminders(s):
    """Remove any inline <system-reminder>...</system-reminder> spans."""
    return re.sub(r"<system-reminder>.*?</system-reminder>", " ", s, flags=re.S)


def clean_text(t):
    """Return cleaned user text, or None if this block is wrapper-only / empty."""
    if not t:
        return None
    stripped = t.lstrip()

    # Slash-command block: keep only the command + args line, drop pasted SKILL body.
    if "<command-name>" in stripped:
        name_m = CMD_NAME_RE.search(stripped)
        args_m = CMD_ARGS_RE.search(stripped)
        name = name_m.group(1).strip() if name_m else ""
        args = args_m.group(1).strip() if args_m else ""
        if not name and not args:
            return None
        combined = (name + " " + args).strip()
        combined = strip_system_reminders(combined).strip()
        return combined[:MAX_TEXT] if combined else None

    # Wrapper-only blocks (system reminders, ide context, hook feedback, caveats).
    low = stripped[:80]
    for w in WRAPPER_PREFIXES:
        if low.startswith(w):
            return None

    # Agent-dispatch / worker-prompt briefs (META-authored, not user-typed).
    for w in AGENT_PROMPT_PREFIXES:
        if stripped.startswith(w):
            return None
    head = stripped[:220]
    for w in AGENT_PROMPT_CONTAINS:
        if w in head:
            return None
    for w in WRAPPER_CONTAINS:
        if w in stripped[:120]:
            # strip inline reminders but keep any remaining real text
            cleaned = strip_system_reminders(stripped).strip()
            # drop residual hook/caveat noise
            if not cleaned or cleaned.startswith(("Caveat:", "Stop hook")):
                return None
            if len(cleaned) < 8:
                return None
            return cleaned[:MAX_TEXT]

    cleaned = strip_system_reminders(stripped).strip()
    cleaned = TAG_STRIP_RE.sub("", cleaned).strip()
    if len(cleaned) < 4:
        return None
    return cleaned[:MAX_TEXT]


def extract_user_texts(message):
    """Yield cleaned user-typed text strings from a message object."""
    c = message.get("content")
    raw_blocks = []
    if isinstance(c, str):
        raw_blocks = [c]
    elif isinstance(c, list):
        for b in c:
            if isinstance(b, dict):
                if b.get("type") == "text":
                    raw_blocks.append(b.get("text", ""))
                # explicitly skip tool_result / image / etc.
            elif isinstance(b, str):
                raw_blocks.append(b)
    for rb in raw_blocks:
        ct = clean_text(rb)
        if ct:
            yield ct


def main():
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    files = sorted(glob.glob(os.path.join(CORPUS_DIR, "*.jsonl")))
    transcripts = 0
    kept = 0
    with open(OUT_PATH, "w", encoding="utf-8") as out:
        for f in files:
            transcripts += 1
            tid = os.path.splitext(os.path.basename(f))[0]
            try:
                with open(f, "r", encoding="utf-8") as fh:
                    for line_no, line in enumerate(fh, 1):
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            o = json.loads(line)
                        except Exception:
                            continue
                        if o.get("type") != "user":
                            continue
                        msg = o.get("message")
                        if not isinstance(msg, dict):
                            continue
                        # role guard (defensive; type==user already implies role user)
                        role = msg.get("role", "user")
                        if role != "user":
                            continue
                        ts = o.get("timestamp")
                        for text in extract_user_texts(msg):
                            rec = {
                                "transcript_id": tid,
                                "line_no": line_no,
                                "approx_ts": ts,
                                "text": text,
                            }
                            out.write(json.dumps(rec, ensure_ascii=False) + "\n")
                            kept += 1
            except Exception as e:
                sys.stderr.write("WARN failed %s: %s\n" % (tid, e))
                continue
    size = os.path.getsize(OUT_PATH)
    print("transcripts scanned : %d" % transcripts)
    print("user messages kept  : %d" % kept)
    print("output path         : %s" % OUT_PATH)
    print("output size         : %d bytes (%.1f KB)" % (size, size / 1024.0))


if __name__ == "__main__":
    main()
