"""Generate alias stub SKILL.md files from SKILL_ALIASES.yaml.

PROBLEM SOLVED
==============
The Claude Code harness gates slash-command invocation on EXACT directory
match against .claude/skills/<name>/. When the user types `/debate`, the
harness looks for `.claude/skills/debate/SKILL.md`. If it doesn't exist,
the command is either dropped by the UI or arrives at Claude as plain
text without the skill-expansion envelope.

A UserPromptSubmit hook can't fix this because hooks can only
add-context or block — they cannot rewrite the prompt (verified against
https://code.claude.com/docs/en/hooks).

SOLUTION
========
For each registered alias (e.g. `debate` -> `dialectic`), create a stub
directory `.claude/skills/<alias>/` containing a SKILL.md that:

1. Has YAML frontmatter so the harness lists it as an available skill
   (= discoverable in /<tab> autocomplete).
2. Tells Claude: "this is an alias for X, read the canonical SKILL.md
   and follow that protocol on the task below".
3. Passes `$ARGUMENTS` through unchanged so the user's task reaches the
   canonical skill verbatim.

For built-in skills (run, verify, loop, schedule, update-config, ...)
the stub instructs Claude to invoke `Skill(skill="<canonical>")` via the
harness Skill tool, because those aren't file-based.

Usage:
    python scripts/gen_alias_stubs.py            # generate
    python scripts/gen_alias_stubs.py --dry-run  # report what would change
    python scripts/gen_alias_stubs.py --clean    # remove existing stubs first

Idempotent: re-running produces the same files. Safe to re-run after
editing SKILL_ALIASES.yaml.
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path


STUB_HEADER = "<!-- AUTOGENERATED by scripts/gen_alias_stubs.py from .claude/skills/_common/SKILL_ALIASES.yaml. DO NOT EDIT BY HAND. -->"


def load_aliases(path: Path) -> tuple[dict[str, list[str]], set[str]]:
    """Parse SKILL_ALIASES.yaml — same logic as fuzzy_slash_match.py.

    Returns:
        (canonical_to_aliases, builtins)
        canonical_to_aliases: {canonical: [alias, ...]}
        builtins: {builtin_name, ...}  (skills shipped with harness)
    """
    canonical_to_aliases: dict[str, list[str]] = {}
    builtins: set[str] = set()
    current_canonical: str | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.rstrip()
        if not s or s.lstrip().startswith("#"):
            continue
        if not s.startswith(" ") and not s.startswith("\t") and s.endswith(":"):
            current_canonical = s[:-1].strip()
            if current_canonical != "__builtins__":
                canonical_to_aliases.setdefault(current_canonical, [])
            continue
        stripped = s.strip()
        if stripped.startswith("- ") and current_canonical:
            alias_raw = stripped[2:].strip()
            if "#" in alias_raw:
                alias_raw = alias_raw.split("#", 1)[0].strip()
            if not alias_raw:
                continue
            alias_lower = alias_raw.lower()
            if current_canonical == "__builtins__":
                builtins.add(alias_lower)
            else:
                canonical_to_aliases[current_canonical].append(alias_lower)
    return canonical_to_aliases, builtins


def existing_skills(skills_root: Path) -> set[str]:
    """Skills that currently exist as directories under .claude/skills/."""
    out: set[str] = set()
    if not skills_root.exists():
        return out
    for p in skills_root.iterdir():
        if p.is_dir() and not p.name.startswith("_"):
            if (p / "SKILL.md").exists():
                out.add(p.name)
    return out


def is_autogen_stub(skill_md: Path) -> bool:
    """True if the SKILL.md is one of our generated stubs (safe to overwrite).

    Scans first 20 lines for the autogen sentinel — the sentinel now lives AFTER
    the YAML frontmatter (so YAML parsing isn't broken), so it's not always on
    line 1.
    """
    if not skill_md.exists():
        return False
    try:
        head = skill_md.read_text(encoding="utf-8").splitlines()[:20]
    except (OSError, UnicodeDecodeError):
        return False
    return any(STUB_HEADER in line for line in head)


def render_project_stub(alias: str, canonical: str) -> str:
    """Stub for a project-skill alias (canonical lives at .claude/skills/<canonical>/).

    YAML frontmatter MUST be the first content of the file (no leading comments)
    or the harness fails to parse the `description:` field and falls back to
    using line 1 as the description string.
    """
    return f"""---
name: {alias}
description: Alias for /{canonical} -- routes to the canonical skill, identical protocol.
argument-hint: "task to run via /{canonical}"
metadata:
  alias_of: {canonical}
  autogenerated: true
---

{STUB_HEADER}

You were invoked via `/{alias}`, which is a registered alias for `/{canonical}`.

**Action**: Read [`../{canonical}/SKILL.md`](../{canonical}/SKILL.md) now and execute its protocol exactly, on the task below. The alias exists only for ergonomics; the protocol is the canonical one. Do NOT improvise; follow `.claude/skills/{canonical}/SKILL.md` verbatim.

## Your Task
$ARGUMENTS
"""


def render_builtin_stub(alias: str, canonical: str) -> str:
    """Stub for an alias whose canonical is a harness built-in skill (no file)."""
    return f"""---
name: {alias}
description: Alias for /{canonical} (harness built-in) -- routes via the Skill tool.
argument-hint: "task to run via /{canonical}"
metadata:
  alias_of: {canonical}
  alias_target_type: builtin
  autogenerated: true
---

{STUB_HEADER}

You were invoked via `/{alias}`, which is a registered alias for the harness built-in `/{canonical}`.

**Action**: Invoke `Skill(skill="{canonical}")` to run the canonical built-in. Pass the task below as the `args`.

## Your Task
$ARGUMENTS
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--dry-run", action="store_true", help="report planned changes; write nothing")
    ap.add_argument("--clean", action="store_true", help="remove existing autogen stubs before regenerating")
    args = ap.parse_args()

    project_root = Path(__file__).resolve().parent.parent
    skills_root = project_root / ".claude" / "skills"
    aliases_path = skills_root / "_common" / "SKILL_ALIASES.yaml"

    if not aliases_path.exists():
        print(f"ERROR: {aliases_path} not found", file=sys.stderr)
        return 2

    canonical_to_aliases, builtins = load_aliases(aliases_path)
    existing = existing_skills(skills_root)
    print(f"Loaded {sum(len(v) for v in canonical_to_aliases.values())} aliases across {len(canonical_to_aliases)} canonicals")
    print(f"Existing project skills: {sorted(existing)}")
    print(f"Built-ins registered: {sorted(builtins)}")

    # Optional clean phase — remove existing autogen stubs FIRST, then re-derive
    # the existing-skills set so the collision check sees the post-clean state.
    if args.clean:
        removed = 0
        for p in skills_root.iterdir():
            if not p.is_dir() or p.name.startswith("_"):
                continue
            stub = p / "SKILL.md"
            if is_autogen_stub(stub):
                if args.dry_run:
                    print(f"  [dry-run] would remove {p.relative_to(project_root)}/")
                else:
                    stub.unlink()
                    try:
                        p.rmdir()
                    except OSError:
                        pass
                removed += 1
        print(f"Clean: {removed} autogen stub(s) removed")
        # Re-capture existing skills now that stubs have been removed; otherwise
        # the collision check below misclassifies just-deleted stubs as "real
        # skills" and skips every alias.
        existing = existing_skills(skills_root)

    created = updated = skipped_collision = 0
    for canonical, alias_list in canonical_to_aliases.items():
        is_builtin_canonical = canonical in builtins
        for alias in alias_list:
            # Skip if alias collides with a real, non-stub skill (don't shadow real work).
            stub_dir = skills_root / alias
            stub_md = stub_dir / "SKILL.md"
            if alias in existing and not is_autogen_stub(stub_md):
                print(f"  SKIP: /{alias} collides with existing real skill -> not shadowing")
                skipped_collision += 1
                continue
            # Skip if alias is a harness built-in (the harness already handles /<builtin>).
            if alias in builtins:
                print(f"  SKIP: /{alias} is itself a harness built-in -> not stubbing")
                skipped_collision += 1
                continue

            if is_builtin_canonical:
                content = render_builtin_stub(alias, canonical)
            else:
                content = render_project_stub(alias, canonical)

            existed = stub_md.exists()
            if args.dry_run:
                action = "update" if existed else "create"
                print(f"  [dry-run] would {action} {stub_md.relative_to(project_root)}")
            else:
                stub_dir.mkdir(parents=True, exist_ok=True)
                stub_md.write_text(content, encoding="utf-8", newline="\n")
                if existed:
                    updated += 1
                else:
                    created += 1

    print()
    print(f"SUMMARY: created={created}  updated={updated}  collision_skipped={skipped_collision}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
