"""Phase-completion notifier.

Sends an email (Gmail SMTP) when invoked, and ALWAYS appends a structured
notification log entry to `runs/notifications/<date>.log`. Designed to be
called between phases of autonomous runs.

Usage:
    python scripts/notify_phase_complete.py \
        --phase "Phase 1: Crawler Suite" \
        --status COMPLETE \
        --summary "5 crawlers shipped, 1 critical bug found + fixed (anti_fragile v51)" \
        --next "Phase 2: WM trainer migration"

Configuration (one-time, via environment variables):
    NOTIFY_SMTP_HOST     default: smtp.gmail.com
    NOTIFY_SMTP_PORT     default: 587
    NOTIFY_FROM          default: <NOTIFY_USER>
    NOTIFY_USER          REQUIRED for SMTP — your Gmail address
    NOTIFY_PASSWORD      REQUIRED for SMTP — Gmail APP PASSWORD (not your login pw)
                         Create at: https://myaccount.google.com/apppasswords
    NOTIFY_TO            default: karabo.manasoe@gmail.com (per project record)

Behaviour:
    - If NOTIFY_USER + NOTIFY_PASSWORD are set: tries SMTP send; logs result
    - If not set: logs notification to file only (no email); exits 0 cleanly
    - Send failures are logged but DO NOT block the autonomous pipeline (exit 0)

Exit codes:
    0  notification logged (and email sent if SMTP configured)
    1  invalid arguments (usage error)

Provenance: 2026-05-17 user directive — "setup email notification script after phase completion"
"""
from __future__ import annotations

import argparse
import json
import os
import smtplib
import sys
import time
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
LOG_DIR = PROJECT_ROOT / "runs" / "notifications"

DEFAULT_TO = "karabo.manasoe@gmail.com"
DEFAULT_HOST = "smtp.gmail.com"
DEFAULT_PORT = 587


def _ensure_log_dir() -> Path:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    return LOG_DIR / f"{datetime.now().strftime('%Y-%m-%d')}.log"


def _log_event(event: dict) -> None:
    path = _ensure_log_dir()
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(event) + "\n")


def _build_body(args: argparse.Namespace) -> str:
    lines = [
        f"PHASE:    {args.phase}",
        f"STATUS:   {args.status}",
        f"TIME:     {datetime.now().isoformat(timespec='seconds')}",
        "",
        "SUMMARY:",
        f"  {args.summary or '(no summary provided)'}",
    ]
    if args.next:
        lines.extend(["", f"NEXT:     {args.next}"])
    if args.detail:
        lines.extend(["", "DETAIL:", *(f"  {ln}" for ln in args.detail.splitlines())])
    if args.artifacts:
        lines.extend(["", "ARTIFACTS:", *(f"  - {a}" for a in args.artifacts.split(','))])
    lines.append("")
    lines.append("---")
    lines.append("Auto-generated by scripts/notify_phase_complete.py")
    return "\n".join(lines)


def send_email(to_addr: str, subject: str, body: str,
               host: str, port: int, user: str, password: str,
               from_addr: str) -> tuple[bool, str]:
    """Send via SMTP-STARTTLS. Returns (success, message)."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.attach(MIMEText(body, "plain"))

    try:
        # 30s timeout — fail fast if SMTP unresponsive
        with smtplib.SMTP(host, port, timeout=30) as s:
            s.ehlo()
            s.starttls()
            s.ehlo()
            s.login(user, password)
            s.sendmail(from_addr, [to_addr], msg.as_string())
        return True, "sent"
    except smtplib.SMTPAuthenticationError as e:
        return False, f"auth_failed: {e}"
    except smtplib.SMTPException as e:
        return False, f"smtp_error: {type(e).__name__}: {e}"
    except (TimeoutError, OSError) as e:
        return False, f"network_error: {type(e).__name__}: {e}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--phase", required=True, help="Phase name (short label)")
    ap.add_argument("--status", default="COMPLETE",
                    choices=["COMPLETE", "FAILED", "PARTIAL", "STARTED", "PROGRESS"],
                    help="Phase status")
    ap.add_argument("--summary", default="", help="One-line summary of what happened")
    ap.add_argument("--next", default="", help="What's queued next (one line)")
    ap.add_argument("--detail", default="",
                    help="Multi-line detail block (use \\n for newlines)")
    ap.add_argument("--artifacts", default="",
                    help="Comma-separated list of artifact paths created this phase")
    ap.add_argument("--to", default=os.environ.get("NOTIFY_TO", DEFAULT_TO),
                    help="Email recipient")
    ap.add_argument("--no-email", action="store_true",
                    help="Skip email send; log only (useful for testing)")
    args = ap.parse_args()

    started_at = time.time()
    subject = f"[V4-CRYPTO] {args.status}: {args.phase}"
    body = _build_body(args)

    event = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "phase": args.phase,
        "status": args.status,
        "summary": args.summary,
        "next": args.next or None,
        "artifacts": args.artifacts.split(",") if args.artifacts else [],
        "email_to": args.to,
    }

    # Determine SMTP config
    user = os.environ.get("NOTIFY_USER", "")
    password = os.environ.get("NOTIFY_PASSWORD", "")
    host = os.environ.get("NOTIFY_SMTP_HOST", DEFAULT_HOST)
    port = int(os.environ.get("NOTIFY_SMTP_PORT", DEFAULT_PORT))
    from_addr = os.environ.get("NOTIFY_FROM", user or "noreply@v4-crypto.local")

    # Print phase summary to stdout (always)
    print("=" * 72)
    print(subject)
    print("=" * 72)
    print(body)
    print("=" * 72)

    # Attempt email send if configured
    if args.no_email or not user or not password:
        if not user or not password:
            print("\n[notify] SMTP credentials NOT SET (NOTIFY_USER / NOTIFY_PASSWORD env vars)")
            print("[notify] To enable email, set:")
            print("[notify]   $env:NOTIFY_USER = 'you@gmail.com'")
            print("[notify]   $env:NOTIFY_PASSWORD = '<app_password from myaccount.google.com/apppasswords>'")
            print("[notify] Notification logged to file (no email sent).")
            event["email_sent"] = False
            event["email_reason"] = "credentials_not_set"
        else:
            print("\n[notify] --no-email flag set; logging only.")
            event["email_sent"] = False
            event["email_reason"] = "no_email_flag"
    else:
        print(f"\n[notify] Sending email to {args.to} via {host}:{port}...")
        ok, msg = send_email(args.to, subject, body, host, port, user, password, from_addr)
        if ok:
            print(f"[notify] EMAIL SENT successfully ({time.time()-started_at:.1f}s)")
        else:
            print(f"[notify] EMAIL FAILED: {msg} (notification logged anyway)")
        event["email_sent"] = ok
        event["email_reason"] = msg if not ok else "ok"

    _log_event(event)
    print(f"[notify] Logged to {_ensure_log_dir()}")

    # Always exit 0 — notification failure should not abort autonomous pipeline
    return 0


if __name__ == "__main__":
    sys.exit(main())
