"""
Liquidity-tier screener for the asset universe.

Reads chimera_legacy dollar bars for every asset under
data/processed/chimera_legacy/dollar/, aggregates to daily $ volume,
takes the 30-day median, and classifies each asset into one of four tiers:

    Tier B (u100-continuous)    : >= $50M/day median volume
    Tier C (u100-capped)        : >= $10M and < $50M/day
    Event-only                  : >=  $1M and < $10M/day
    Drop                        :  <  $1M/day

Outputs:
    1. Stdout: ranked table + tier counts + diff vs current u50/u100 yaml
    2. logs/universe_screen_<DATE>.csv: full per-asset row with all metrics
    3. logs/universe_screen_<DATE>.proposed_u100.yaml: drop-in replacement
       for config/universes/u100.yaml (REVIEW BEFORE OVERWRITING)
    4. logs/universe_screen_<DATE>.event_universe.yaml: event-only universe
       seed for the hunter sleeve

The pipeline build is UNAFFECTED — chimera continues to build for whatever
raw data exists. Tiers are downstream metadata.

Usage:
    python scripts/screen_universe_by_liquidity.py
    python scripts/screen_universe_by_liquidity.py --thresh-b 50e6 --thresh-c 10e6
    python scripts/screen_universe_by_liquidity.py --window-days 60      # longer baseline
    python scripts/screen_universe_by_liquidity.py --apply                # write yamls in place
"""
from __future__ import annotations

import argparse
import csv
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import polars as pl

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src" / "pipeline"))

CHIM_DIR = PROJECT_ROOT / "data" / "processed" / "chimera_legacy" / "dollar"
LOG_DIR  = PROJECT_ROOT / "logs"

# Default tier thresholds
THRESH_B_DEFAULT = 50_000_000.0   # $50M/day -> u100 continuous
THRESH_C_DEFAULT = 10_000_000.0   # $10M/day -> u100 capped
THRESH_EVT_DEF   = 1_000_000.0    # $1M/day  -> event only

WINDOW_DAYS_DEFAULT = 30          # rolling window for volume median


def _asset_from_filename(p: Path) -> Optional[str]:
    """Extract uppercase symbol from chimera_legacy filename.

    Filename pattern: <sym>usdt_v50_chimera_<YYYYMMDD>.parquet
    """
    stem = p.stem.lower()
    if "usdt_" not in stem:
        return None
    sym_l = stem.split("usdt_", 1)[0]
    return sym_l.upper() + "USDT"


def daily_dollar_volume(parquet_path: Path,
                        window_days: int = WINDOW_DAYS_DEFAULT) -> Tuple[float, int]:
    """Return (median daily $ volume, n_days_observed) for an asset.

    Uses the most recent `window_days` of data. If the file has fewer days,
    uses what's available. Returns (NaN, 0) on read error.
    """
    try:
        df = pl.scan_parquet(parquet_path).select(["timestamp", "volume_usd"]).collect()
    except Exception:
        return (float("nan"), 0)
    if len(df) == 0:
        return (float("nan"), 0)

    # Convert timestamp (ms) -> Date
    df = df.with_columns(
        pl.from_epoch(pl.col("timestamp"), time_unit="ms").dt.date().alias("date")
    )
    daily = (
        df.group_by("date")
          .agg(pl.col("volume_usd").sum().alias("daily_vol"))
          .sort("date")
    )
    n = len(daily)
    if n == 0:
        return (float("nan"), 0)
    recent = daily.tail(window_days)
    median = float(recent["daily_vol"].median() or float("nan"))
    return (median, len(recent))


def classify(median_vol: float,
             thresh_b: float, thresh_c: float, thresh_evt: float) -> str:
    if median_vol != median_vol:                # NaN
        return "DROP_NO_DATA"
    if median_vol >= thresh_b:
        return "TIER_B"
    if median_vol >= thresh_c:
        return "TIER_C"
    if median_vol >= thresh_evt:
        return "EVENT_ONLY"
    return "DROP"


def load_existing_universe(name: str) -> List[str]:
    try:
        from universe_loader import UniverseLoader
        return [s.upper() for s in UniverseLoader.load().list(name)]
    except Exception as e:
        print(f"[WARN] could not load universe {name}: {e}", file=sys.stderr)
        return []


def emit_yaml(tier: str, assets: List[str], out_path: Path) -> None:
    """Write a minimal yaml seed (the user can refine + merge by hand)."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        f"# Auto-generated by scripts/screen_universe_by_liquidity.py on {today}",
        f"# Tier: {tier}",
        f"# REVIEW BEFORE OVERWRITING canonical universe yaml.",
        "",
    ]
    if tier == "u100_proposed":
        lines += [
            "name: u100",
            "inherit_from: u50",
            "extra_assets:",
        ]
    else:
        lines += [
            f"name: {tier}",
            "assets:",
        ]
    for a in sorted(assets):
        lines.append(f"  - symbol: {a}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--thresh-b",   type=float, default=THRESH_B_DEFAULT,
                    help=f"$/day for Tier B (continuous); default {THRESH_B_DEFAULT:.0f}")
    ap.add_argument("--thresh-c",   type=float, default=THRESH_C_DEFAULT,
                    help=f"$/day for Tier C (capped); default {THRESH_C_DEFAULT:.0f}")
    ap.add_argument("--thresh-evt", type=float, default=THRESH_EVT_DEF,
                    help=f"$/day for Event-only; default {THRESH_EVT_DEF:.0f}")
    ap.add_argument("--window-days", type=int, default=WINDOW_DAYS_DEFAULT,
                    help=f"rolling window for median (days); default {WINDOW_DAYS_DEFAULT}")
    ap.add_argument("--apply", action="store_true",
                    help="Overwrite config/universes/u100.yaml in place "
                         "(default: write proposed yaml to logs/ for review).")
    args = ap.parse_args()

    if not CHIM_DIR.exists():
        print(f"[error] no chimera_legacy at {CHIM_DIR}; run pipeline first", file=sys.stderr)
        return 1

    files = sorted(CHIM_DIR.glob("*usdt_v50_chimera*.parquet"))
    if not files:
        print(f"[error] no chimera files in {CHIM_DIR}", file=sys.stderr)
        return 1

    print(f"Screening {len(files)} chimera files (window={args.window_days}d)...")
    print()

    rows: List[dict] = []
    for fp in files:
        sym = _asset_from_filename(fp)
        if sym is None:
            continue
        med_vol, n_days = daily_dollar_volume(fp, window_days=args.window_days)
        tier = classify(med_vol, args.thresh_b, args.thresh_c, args.thresh_evt)
        rows.append({
            "asset":        sym,
            "median_$vol":  med_vol,
            "n_days":       n_days,
            "tier":         tier,
            "file":         fp.name,
        })

    rows.sort(key=lambda r: r["median_$vol"] if r["median_$vol"] == r["median_$vol"] else -1.0,
              reverse=True)

    # Reference universes
    u10  = set(load_existing_universe("u10"))
    u50  = set(load_existing_universe("u50"))
    u100 = set(load_existing_universe("u100"))

    # ─── Print ranked table ─────────────────────────────────────────────
    print(f"{'#':>3}  {'asset':<14} {'median $/day':>15}  {'days':>4}  {'tier':<14} {'in u50':<6} {'in u100':<7}")
    print("-" * 78)
    tier_counts: Dict[str, int] = {}
    tier_assets: Dict[str, list] = {"TIER_B": [], "TIER_C": [],
                                      "EVENT_ONLY": [], "DROP": [],
                                      "DROP_NO_DATA": []}
    for i, r in enumerate(rows, 1):
        a = r["asset"]
        v = r["median_$vol"]
        tier = r["tier"]
        tier_counts[tier] = tier_counts.get(tier, 0) + 1
        tier_assets[tier].append(a)
        v_str = f"${v:>13,.0f}" if v == v else "    (no data) "
        in_u50 = "Y" if a in u50 else "-"
        in_u100 = "Y" if a in u100 else "-"
        print(f"{i:>3}  {a:<14} {v_str:>15}  {r['n_days']:>4}  {tier:<14} {in_u50:<6} {in_u100:<7}")

    print()
    print("Tier counts:")
    for tier in ["TIER_B", "TIER_C", "EVENT_ONLY", "DROP", "DROP_NO_DATA"]:
        n = tier_counts.get(tier, 0)
        print(f"  {tier:<14} {n:>3}")
    print()

    # ─── Diff vs current u100 ───────────────────────────────────────────
    current_extras = u100 - u50
    proposed_b_c = set(tier_assets["TIER_B"] + tier_assets["TIER_C"])
    proposed_extras = proposed_b_c - u50          # everything liquid that's not already in u50
    add_to_u100 = sorted(proposed_extras - current_extras)
    drop_from_u100 = sorted(current_extras - proposed_extras)

    print(f"Current u100 extras (beyond u50): {len(current_extras)}")
    print(f"Proposed u100 extras:             {len(proposed_extras)}")
    print()
    print(f"ADD to u100 ({len(add_to_u100)}):  {', '.join(add_to_u100[:10])}"
          + (f" ... +{len(add_to_u100)-10} more" if len(add_to_u100) > 10 else ""))
    print(f"DROP from u100 ({len(drop_from_u100)}): {', '.join(drop_from_u100[:10])}"
          + (f" ... +{len(drop_from_u100)-10} more" if len(drop_from_u100) > 10 else ""))
    print()

    # ─── Persist output files ───────────────────────────────────────────
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y%m%d")
    csv_path  = LOG_DIR / f"universe_screen_{today}.csv"
    u100_path = LOG_DIR / f"universe_screen_{today}.proposed_u100.yaml"
    evt_path  = LOG_DIR / f"universe_screen_{today}.event_universe.yaml"

    with open(csv_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["asset", "median_$vol", "n_days", "tier",
                                            "in_u50", "in_u100", "file"])
        w.writeheader()
        for r in rows:
            r2 = dict(r)
            r2["in_u50"]  = "Y" if r["asset"] in u50  else "-"
            r2["in_u100"] = "Y" if r["asset"] in u100 else "-"
            w.writerow(r2)
    print(f"CSV:                  {csv_path.relative_to(PROJECT_ROOT)}")

    # Proposed u100: u50 (inherited) + Tier B/C extras
    emit_yaml("u100_proposed", sorted(proposed_extras), u100_path)
    print(f"Proposed u100 yaml:   {u100_path.relative_to(PROJECT_ROOT)}")

    # Event universe: Tier EVENT_ONLY assets
    emit_yaml("event_universe", sorted(tier_assets["EVENT_ONLY"]), evt_path)
    print(f"Event universe yaml:  {evt_path.relative_to(PROJECT_ROOT)}")

    if args.apply:
        target = PROJECT_ROOT / "config" / "universes" / "u100.yaml"
        target.write_text(u100_path.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"\n[APPLIED] overwrote {target.relative_to(PROJECT_ROOT)}")
        evt_target = PROJECT_ROOT / "config" / "universes" / "event.yaml"
        evt_target.write_text(evt_path.read_text(encoding="utf-8"), encoding="utf-8")
        print(f"[APPLIED] overwrote {evt_target.relative_to(PROJECT_ROOT)}")
    else:
        print("\n(use --apply to overwrite the canonical yaml in place)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
